version: '3.8'

services:
  server:
    build: .
    container_name: rust_server
    ports:
      - "34254:34254/udp"
    volumes:
      - ./data:/usr/src/app/data
    healthcheck:
      test: ["CMD", "pgrep", "server"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
